name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches: [ main,master ]
  pull_request:
    branches: [ main ,master ] # merge到main分支时触发部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@master

      - name: 设置环境 Golang 环境
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: 构建 BuiLd
        run: |
          go build -o app
          ls

      - name: 同步文件
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./app
          remote_path: /myapp
          remote_host: 121.5.70.28
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.DeploySecret }}
